# Generated by Django 2.1.3 on 2018-11-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineerlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='displayname',
            field=models.CharField(max_length=20, verbose_name='display_name'),
        ),
    ]
