# Generated by Django 2.1.3 on 2018-11-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineerlog', '0002_auto_20181130_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='displayname',
            field=models.CharField(max_length=20, verbose_name='表示名'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.DurationField(verbose_name='duration'),
        ),
    ]
