# Generated by Django 2.1.3 on 2018-11-29 18:28

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('engineerlog', '0003_auto_20181130_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='media/default_icon/default.JPG', upload_to='icons/', verbose_name='アイコン'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='profile_sentence',
            field=models.TextField(blank=True, verbose_name='プロフィール文'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.TextField(verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.DurationField(verbose_name='勉強時間'),
        ),
    ]
