# Generated by Django 2.1.3 on 2018-11-29 18:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('engineerlog', '0004_auto_20181130_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/default.JPG', upload_to='icons/', verbose_name='アイコン'),
        ),
    ]
